### PR TITLE
Add aragorn

### LINKED ISSUE #18: Add Aragorn

### PR DESCRIPTION
**Pull request by RNAer**
Fix #18

### CODE REVIEW

**Comment by mortonjt** [comment]
What's left on this PR?

**Comment by RNAer** [comment]
nothing. it's ready to be merged

**Comment by Jorge-C** [comment]
The compilation instructions mentioned that there should be a man page, but the env variable that should have that information is empty in Ubuntu, so I think this is good. Merged!

**Comment by RNAer** [comment]
@Jorge-C , in a retrospect on that, I can move the man page file to `$PREFIX/man/man1/`?

**Comment by Jorge-C** [comment]
Sure, is that the right location? I don't know how man works, and the env variable that should have that info according to their build instructions was empty in ubuntu 14.04.

**Comment by RNAer** [comment]
I guess so, if you check you anaconda/envs/xxx_env/man. Some have man files
in that, some have them in a further dir `share/man`. btw, isn't the env
var for man `MANPATH`?

**Comment by Jorge-C** [comment]
Cool, :+1:

2015-11-10 17:16 GMT-07:00 Zech Xu notifications@github.com:

> I guess so, if you check you anaconda/envs/xxx_env/man. Some have man files
> in that, some have them in a further dir `share/man`. btw, isn't the env
> var for man `MANPATH`?
> 
> On Tue, Nov 10, 2015 at 4:06 PM, Jorge Cañardo Alastuey <

**Comment by RNAer** [comment]
but conda doesn't change `MANPATH` when one activates or deactivates an
env. modify all the relevant env var besides `PATH` should be an easy
feature for conda to have ...

**Pull request merged**
