### PR TITLE
add vsearch recipe

### PR DESCRIPTION
**Pull request by colinbrislawn**
Add recipe for vsearch.

I'm submitting a pull request to see if it uploads correctly after building.

Don't merge yet! I would like to receive input from @torognes before adding this. See torognes/vsearch#134

### CODE REVIEW

**Comment by wasade** [comment]
:+1: \* :100:

**Comment by torognes** [comment]
Looks good!

**Comment by colinbrislawn** [comment]
Thanks @torognes!
:shipit:

**Comment by ElDeveloper** [comment]
:+1:

**Comment by colinbrislawn** [comment]
While vsearch builds correctly, the travis build fails afterwards with this error.

Is this related to biocore/conda-recipes#2

Should I upload this to binstar manually? 

```
TEST END: vsearch-1.8.0-0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /Users/travis/miniconda/conda-bld/osx-64/vsearch-1.8.0-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
CHECKING COMMAND: conda search --json --override-channels -c https://conda.anaconda.org/biocore --spec vsearch=1.8.0
UPLOADING COMMAND: anaconda -t {token} upload -u biocore {built}
Traceback (most recent call last):
  File "ci/main.py", line 58, in <module>
    build_upload_recipes(sys.argv[1])
  File "ci/main.py", line 22, in build_upload_recipes
    build_upload(name, version, root)
  File "ci/main.py", line 53, in build_upload
    token=environ['ANACONDA_TOKEN'], built=built),
  File "/Users/travis/miniconda/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'ANACONDA_TOKEN'
The command "python ci/main.py recipes" exited with 1.
```

**Comment by colinbrislawn** [comment]
Looks like this is because the `'ANACONDA_TOKEN'` is missing from `.travis.yaml`. 

@Jorge-C and @RNAer, can you take a look at this?

**Comment by RNAer** [comment]
@colinbrislawn , interesting, the token should be valid untill 2016 July to update. It could also be due to the glitches of Travis. I have multiple times of debuging non-existing bugs in the past weeks because of false Travis fails, resulting in wasting many hours. I would wait for 1-2 days to restart the Travis CI to see how it goes.

**Comment by RNAer** [comment]
and at the same, I think it is fine to upload vsearch to biocore mannually if it is urgent

**Comment by colinbrislawn** [comment]
I'd like to get the automated process set up, because that's the long term solution.

I don't think this is a bug. As far as I can tell, this repo has never completed a build by uploading a new package to binstar. Previous builds have been successful because their packages already exist.
https://travis-ci.org/biocore/conda-recipes

**Comment by colinbrislawn** [comment]
Hello @Jorge-C,

Could you take a look at this Travis build and help me understand what is going wrong?

The [error](https://travis-ci.org/biocore/conda-recipes/jobs/87572870#L3257) occurs the very first time the anaconda token is used to upload a built package to the site. 

Perhaps `ANACONDA_TOKEN` was encrypted strangely? 

Thank you!
Colin

**Comment by Jorge-C** [comment]
Hi Colin, I'll take a look!

**Comment by Jorge-C** [comment]
According to travis-ci [docs](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables), secure env. variables are not exposed in "untrusted" builds, like PRs. This makes sense, because otherwise you could send a PR that just does `echo $ANACONDA_TOKEN` and we'd no longer have a secret.

**Comment by Jorge-C** [comment]
Let's see if my PR #11 solves this.

**Comment by colinbrislawn** [comment]
Oh that makes complete sense! You would not want someone to upload to the biocore binstar account until you trusted their contribution. 

If sounds like if this built from the master branch, not a PR, it would be successful. Is there anything I should add for unit tests, or is this read to merge?

**Comment by Jorge-C** [comment]
Let's merge #11, restart the build here, and merge when green. Thanks @colinbrislawn!

**Comment by colinbrislawn** [comment]
Thank you! Your experience and support is really wonderful.

**Comment by Jorge-C** [comment]
Thank _you_ for contributing!

There's no need to close this PR, right? We'd still wanted it merged!

**Comment by colinbrislawn** [comment]
Oh, I though you included all these in your PR. I can reopen it if you want.

**Comment by Jorge-C** [comment]
Yes, please reopen it, the other PR "fixes" uploading but doesn't include your changes.

**Comment by Jorge-C** [comment]
Hi @colinbrislawn, do you mind rebasing on top of master? Something like this, depending on config:

```
git checkout you-feature-branch
git rebase upstream/master
```

**Comment by colinbrislawn** [comment]
Sure thing. I'll do that later today.

**Comment by colinbrislawn** [comment]
I've added build number to this PR. Anything else I should do?

@RNAer brings up an interesting use case in #23 when he adds tests that do not ship with the original software package. VSEARCH _does_ ship with tests, but they are benchmarks against USEACH instead of typical unit tests.

How much should our recipes extend the testing of the original packages?

**Comment by colinbrislawn** [comment]
I've rebased this. It should be ready to merge.

**Comment by RNAer** [comment]
Thanks, @colinbrislawn ! As on testing, it's fine to just make sure the built executable is runnable. If there are test case(s) that can be easily included, it is great to include them for sure.

**Pull request merged**
