### PR TITLE
need to check the cmd run to produce error

### PR DESCRIPTION
**Pull request by RNAer**
the error was not raised when build failed. Added check to the cmd run. @wasade , could you review and merge it? and then you can patch your q2-deblur recipe.

### CODE REVIEW

**Comment by wasade** [comment]
Seems good, will merge when green

**Comment by RNAer** [comment]
don't think it will be green because the error in current q2-deblur recipe

**Comment by wasade** [comment]
I restarted the tests because of the merge of the q2 deblur update. It looks green now?

**Comment by wasade** [comment]
good to merge?

**Pull request merged**
