### PR TITLE
Bump req to >=1.0.2

### PR DESCRIPTION
**Pull request by wasade**

### CODE REVIEW

**Comment by mortonjt** [comment]
Don't you need to have a new release on github?  It looks like the last release was made 13 days ago.

**Comment by wasade** [comment]
q2-deblur deps on deblur >= 1.0.1, so don't actually need to make a change though we could i suppose

**Comment by mortonjt** [comment]
I don't think so
https://github.com/wasade/q2-deblur/releases

The q2-deblur build won't be updated without an updated release

**Comment by wasade** [comment]
Looks like its a typo on the title

https://github.com/wasade/q2-deblur/blob/2017.2.3/setup.py#L15

**Comment by wasade** [comment]
And it looks like it is pulling down 1.0.2 

https://travis-ci.org/biocore/conda-recipes/jobs/213150435#L616

**Comment by wasade** [comment]
can this be merged?

**Pull request merged**
