### PR TITLE
Recipe for q2-deblur

### PR DESCRIPTION
**Pull request by wasade**
I think this is inline with what is necessary...

### CODE REVIEW

**Comment by wasade** [comment]
This pulled down deblur 0.1.8 unfortunately. I'll investigate tonight, am on phone until then

**Comment by wasade** [comment]
So this I believe just depends on #73 being merged

**Comment by wasade** [comment]
Failures now are associated with an untagged q2-deblur repo I believe. Investigating.

**Comment by wasade** [comment]
BAM!!

@mortonjt @RNAer eh??? Don't merge yet. Review would be awesome to have if possible. Sending an email out-of-band in a moment

**Comment by RNAer** [comment]
👍

**Comment by wasade** [comment]
I think its passing?

**Comment by RNAer** [comment]
yep. I didn't merge because you asked so. let me know if you want it.

**Comment by wasade** [comment]
i think its good to go

**Comment by wasade** [comment]
Thanks!!

**Pull request merged**
