### PR TITLE
Bump for q2-deblur support with deblur 1.0.1

### PR DESCRIPTION
**Pull request by wasade**

### CODE REVIEW

**Comment by wasade** [comment]
@RNAer @mortonjt should be quick, just bumping the base q2-deblur requirement and removing redundant dependencies

**Comment by mortonjt** [comment]
Awesome!

**Comment by mortonjt** [comment]
Looks like the tests failed :(

**Comment by wasade** [comment]
because conda threw a runtimeerror...
https://travis-ci.org/biocore/conda-recipes/jobs/208677453#L826

**Comment by wasade** [comment]
Oh, I see the issue now

**Comment by mortonjt** [comment]
Looks like python=3.5 is still failing ...

**Review by mortonjt — APPROVED** [review]

**Comment by wasade** [comment]
@mortonjt indicated a :+1: via gchat but was not in a position to merge and asked me to do so

**Pull request merged**
