### PR TITLE
Fix diamond

### LINKED ISSUE #16: Add Diamond

### PR DESCRIPTION
**Pull request by RNAer**
Fix #16 , #41 , and #35 .

### CODE REVIEW

**Comment by mortonjt** [comment]
Hmmm. I'm still getting the following error when I try to test this build on my osx.

```
dyld: lazy symbol binding failed: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Users/mortonjt/miniconda2/envs/_test/bin/diamond
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Users/mortonjt/miniconda2/envs/_test/bin/diamond
  Expected in: /usr/lib/libstdc++.6.dylib

/Users/mortonjt/miniconda2/conda-bld/test-tmp_dir/run_test.sh: line 3: 14191 Trace/BPT trap: 5       diamond -h
TESTS FAILED: diamond-0.7.10-1
```

**Comment by RNAer** [comment]
It is not uploaded to anaconda until merged. You were still installing the old one.

@Jorge-C , would mind taking a look at this PR?

**Comment by mortonjt** [comment]
I didn't use the upload to anaconda - I used conda build.

That's the correct way to test it right?

**Comment by RNAer** [comment]
I tested it again by building locally. don't see problem on my mac...

**Comment by mortonjt** [comment]
Just found out that there was some left over crap in my virtualenv.

So :+1:

**Comment by mortonjt** [comment]
Something funky is going on, when I run

`conda build Diamond`

I get

``` bash
+ make
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_encoding.o algo/blast/core/blast_encoding.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_stat.o algo/blast/core/blast_stat.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_filter.o algo/blast/core/blast_filter.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_util.o algo/blast/core/blast_util.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_message.o algo/blast/core/blast_message.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/ncbi_erf.o algo/blast/core/ncbi_erf.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_options.o algo/blast/core/blast_options.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/ncbi_math.o algo/blast/core/ncbi_math.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_program.o algo/blast/core/blast_program.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/ncbi_std.o algo/blast/core/ncbi_std.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_psi_priv.o algo/blast/core/blast_psi_priv.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/raw_scoremat.o algo/blast/core/raw_scoremat.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_query_info.o algo/blast/core/blast_query_info.c
gcc -O3 -DNDEBUG -c -o algo/blast/core/blast_seg.o algo/blast/core/blast_seg.c
g++ -O3 -DNDEBUG -Iboost/include -Wall -Wno-uninitialized -march=native -c -o main.o main.cpp
main.cpp:23:10: fatal error: 'boost/program_options.hpp' file not found
#include <boost/program_options.hpp>
         ^
1 error generated.
make: *** [main.o] Error 1
```

But when I run
`conda install --use-local Diamond`

Its able to install Diamond just fine.

Not sure if this is a problem.  Otherwise, we should try to get this merged.

**Comment by RNAer** [comment]
I thought you tested it previously?

Firstly,  do you have boost (> 1.53)? And, do you have an already built one
in local dir?

**Comment by mortonjt** [comment]
I just ditched homebrew, in favor of macports.  Its working on my machine now.

**Comment by mortonjt** [comment]
@RNAer , @Jorge-C want to merge this?

**Pull request merged**
