### PR TITLE
Microbiota

### PR DESCRIPTION
**Pull request by Jorge-C**
Prodigal was tricky because they do some non standard stuff, everything else was relatively straightforward.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
:tada: awesome!!!

**Comment by wasade** [comment]
:+1: this is great to see!

**Comment by RNAer** [comment]
ok for merge? is it necessary to put some mechanism of test in place?

**Comment by Jorge-C** [comment]
Some testing happens automatically at package build time.

I created an issue about automatic testing, #2

**Comment by RNAer** [comment]
@Jorge-C , I pulled down your recipes, added Travis CI and issued a new PR here #5

**Pull request merged**
