### PR TITLE
Add biom-format

### PR DESCRIPTION
**Pull request by colinbrislawn**
Addresses #36.

Built using [`conda skeleton`](http://conda.pydata.org/docs/commands/build/conda-skeleton.html). 

Uses most recent biom-format release, not the absolutely newest version on github.

### CODE REVIEW

**Comment by Jorge-C** [comment]
I recall some PR in biom removing pyqi, although it had to be kept for some compatibility issue. Maybe it works even if we drop it here as a requierement (so that we don't have to also build its recipe)?

Also, remember to add h5py to get biom 2.0 files by default.

**Comment by colinbrislawn** [comment]
Yep. Build fails because `pyqi` is not a package for linux-64 and osx-64.

When `pyqi` is dropped as a requirements, the script tried to download it and is killed because `Setuptools downloading is disabled in conda build.`

Also, is there anything specific I need to do to support h5py other then list it as a dependency? 
(Thanks for helping me though this. This is my first time using conda.)

**Comment by Jorge-C** [comment]
We could just create a conda recipe for pyqi in the mean time.

I don't understand why pyqi is still installed with biom, given that it's no longer used.

**Comment by colinbrislawn** [comment]
Yeah, it's odd. `pyqi` only appears twice in the code. Neither should be called when running python 3, like we do here.
https://github.com/biocore/biom-format/search?q=pyqi&type=Code

**Comment by wasade** [comment]
Pyqi was removed on the latest release of BIOM, 2.1.5

**Comment by Jorge-C** [comment]
But it's still required in the setup.py file (due to qiime compatibility
according to a comment). Do you know why that mention could not be removed?

2015-11-17 2:31 GMT+01:00 Daniel McDonald notifications@github.com:

**Comment by wasade** [comment]
Can you link directly? On phone

**Comment by colinbrislawn** [comment]
pyqi in biom-format:
https://github.com/biocore/biom-format/blob/fa6329f39e3462fb1c0bbe5d2ad94e4f7e28f76e/setup.py#L84-L87

**Comment by wasade** [comment]
Thanks. Ugh. I don't recall what specifically this was for. @gregcaporaso?

**Comment by colinbrislawn** [comment]
Because this conda-recipes package only uses python 3.5, that line should never be run. Is conda 'helping' us by identifying this potential dependency?

**Comment by colinbrislawn** [comment]
pyqi also appears here, if that matters:
https://github.com/biocore/biom-format/blob/5f3405f056644771216ea35268114aa24a705478/.travis.yml#L21

**Comment by wasade** [comment]
Ya, to support a no deps install

**Comment by colinbrislawn** [comment]
The pyqi hack in biom-format was added really recently.
https://github.com/biocore/biom-format/commit/7debccd8ac619dbd2b3938fb0870350595030ffd

Perhaps we can remove it now as we transition towards python 3? Maybe @jairideout has a better idea of how to handle this.

**Comment by jairideout** [comment]
Installing pyqi is necessary because QIIME requires it to be present in `print_qiime_config.py` (it raises an error otherwise). This hack is necessary for biom-format releases compatible with QIIME 1.9.x. The hack could be removed if there is another QIIME release (1.9.2) but we're not planning on that unless there are critical bugs to be fixed.

**Comment by ElDeveloper** [comment]
We are planning a maintenance emperor release sometime soon, we could
add pyqi somewhere in there, but that sadly would just be a band-aid.
Just wanted to bring this up in case this actually becomes a bigger
problem.

**Comment by wasade** [comment]
Ah, thanks @jairideout, that was the annoyance...

We could also hackishly bump biom to 2.2.0 which would put it outside of the qiime dependency requirements.

**Comment by colinbrislawn** [comment]
> hackishly bump biom to 2.2.0 

I like it! :shipit: 

Plus, the features `biom from-uc` and h5py support were recently added. I feel like those deserve a minor version bump.

**Comment by colinbrislawn** [comment]
Thanks to @bgruening, there are now great build recipies for `biom-format` versions `2.1.4` and `2.1.5` over in the [bioconda-recipes repo](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/biom-format) and avaiable on [anaconda](https://anaconda.org/bioconda/biom-format/files). 

Let's avoid redundancy and duplicate effort.

**Comment by bgruening** [comment]
In related news: https://github.com/mulled/mulled/pull/71

This automatically creates you a minimal docker image out of conda packages.
Here is the mothur Docker Image: https://quay.io/repository/mulled/mothur

**Comment by bgruening** [comment]
In related news: https://github.com/mulled/mulled/pull/77 :)
Here are the Docker containers: https://quay.io/repository/mulled/qiime & https://quay.io/repository/mulled/biom-format

**Comment by colinbrislawn** [comment]
Thanks for the update!
This is only 20% related, but can you tell me more about quay.io? How do you use it? Why use quay.io over say, AWS, or Travis-CI, or local servers?

**Comment by bgruening** [comment]
@colinbrislawn quay.io is a dockerhub. It just stores Docker images. It does not offer computational power or any testing like traivs.

The following command will import qiime in a isolated Docker container.

```
docker run quay.io/mulled/qiime:1.9.1--py27_0 python -c 'import qiime2'
```

**Comment by colinbrislawn** [comment]
Ah so it holds dockers for docker deployment? Cool. The docker infrastructure could be a good way to ship out all the qiime dependencies (no pun intended). Not sure how many people use docker in amplicon analysis. 

Have you had a better experience with Docker than with, say, Mini Conda?

**Comment by bgruening** [comment]
I have with both technologies good experience. Both are really different but there are users, especially workflow managment systems that do prefer one or the other. Now you get both :)

**Pull request closed without merging**
