### PR TITLE
Add Minced

### LINKED ISSUE #15: Add MinCED

### PR DESCRIPTION
**Pull request by RNAer**
Fix #15

### CODE REVIEW

**Comment by Jorge-C** [comment]
Did you upload it manually to anaconda? It didn't even try building it b/c it's already up.

**Comment by RNAer** [comment]
That was because of the travis test had been done on my forked repo (before merging of the code).

**Comment by Jorge-C** [comment]
Looks good :+1:

**Comment by RNAer** [comment]
ah, let me change the build number to make sure the build is ok. and a
first test on build number. (I feel like we need to add unittest to the
python code.)

**Comment by Jorge-C** [comment]
Yep, I haven't any great suggestions on testing, but we could mock a few
answers from the anaconda server, and starting adding tests cases at least
for bugs we find.

2015-10-30 16:37 GMT-06:00 Zech Xu notifications@github.com:

> ah, let me change the build number to make sure the build is ok. and a
> first test on build number. (I feel like we need to add unittest to the
> python code.)
> 
> On Fri, Oct 30, 2015 at 3:24 PM, Jorge Cañardo Alastuey <

**Comment by RNAer** [comment]
@Jorge-C , feel free to merge it.

**Comment by Jorge-C** [comment]
Sure, biocore admins, can I get write rights for conda-recipes? Thanks!

**Comment by emperor-helper** [comment]
:sparkles:

**Comment by Jorge-C** [comment]
Thanks for the magic!

**Pull request merged**
