### PR TITLE
Adding swarm

### LINKED ISSUE #51: add Swarm
Useful for the EMP project and a useful alternative to vsearch and SortMeRNA.
https://github.com/torognes/swarm

### PR DESCRIPTION
**Pull request by colinbrislawn**
This failed to build locally, but my mac is old. I'll see what happens on Travis-CI.

### CODE REVIEW

**Comment by colinbrislawn** [comment]
@frederic-mahe, I've wrapped up swarm in a conda package to make it easier to install with qiime. Let me know what you think. Suggestions are welcome!

**Comment by frederic-mahe** [comment]
Thanks @colinbrislawn!

**Comment by RNAer** [comment]
looks good to me. @colinbrislawn , is it ready to be merged?

**Comment by colinbrislawn** [comment]
Oh, I should update to the next patch. 
Once this builds, then yes, it's ready to be merged.

**Comment by colinbrislawn** [comment]
Hey Zach, @RNAer :shipit:

**Comment by RNAer** [comment]
:+1:

**Pull request merged**
