### PR TITLE
Add FastTree 2.1.8

### PR DESCRIPTION
**Pull request by colinbrislawn**
All versions built with double precision. The openMP version `FastTreeMP` is built on linux.

### CODE REVIEW

**Comment by colinbrislawn** [comment]
Before merging, we should note that qiime expects 2.1.3 and will fail unit tests with this version. 
@wasade recommends this new version, but IDK if we should temperately move to a newer version then qiime supports.

**Comment by RNAer** [comment]
I think it's fine to put latest version in. current qiime 1.9 does not point to conda for fasttree installation. and qiime 2 will presumably use the latest version.

If you think so as well, we can merge it.

**Comment by Jorge-C** [comment]
@colinbrislawn what's the status for this? I agree with Zech's assessment, but do you see any other issues?

**Comment by colinbrislawn** [comment]
I think it's ready. :shipit:

**Comment by Jorge-C** [comment]
Great, thank you!

**Pull request merged**
