### PR TITLE
Adding RDP Tools

### PR DESCRIPTION
**Pull request by colinbrislawn**
Addresses #39.

Not ready yet, as there is an error when downloading RDP Tools, see rdpstaff/RDPTools#7

### CODE REVIEW

**Comment by colinbrislawn** [comment]
The `.jar` files for the RDP classifier is huge. Like 500 Mb or so. Is that a problem, or inconvenience, or a non-issue?

**Comment by colinbrislawn** [comment]
Fixing issue with Apache Commons dependancies, rdpstaff/RDPTools#8

**Comment by colinbrislawn** [comment]
This builds fine on Linux.

I need to get `ant` working on osx. Should be easy
https://docs.travis-ci.com/user/languages/java/#Projects-Using-Ant

**Comment by colinbrislawn** [comment]
@Jorge-C @RNAer @gregcaporaso 

All set! :shipit:

**Comment by RNAer** [comment]
:+1:

**Pull request merged**
