### PR TITLE
Gneiss version update

### PR DESCRIPTION
**Pull request by mortonjt**
This is updating the gneiss version.

@gregcaporaso @jairideout @ebolyen there is still something weird going on with the scikit-bio conda install here.  But it seems to be ok when I pip install scikit-bio instead.

### CODE REVIEW

**Comment by jairideout** [comment]
What problem are you having specifically with the scikit-bio conda install? Note that scikit-bio 0.5.1 isn't in the default Anaconda channel yet (we don't have control over that). It is available in the `biocore` channel though.

**Comment by mortonjt** [comment]
Oh.  That's probably what is going on - probably it is looking within the anaconda channel.  Will that be available in the anaconda channel eventually?

When I try to build it locally, I get this error
```
(gneiss_recipe) tests-mbp-4:recipes mortonjt$ conda build gneiss
BUILD START: gneiss-0.2.0-py35_0
updating index in: /Users/mortonjt/miniconda3/conda-bld/osx-64
updating index in: /Users/mortonjt/miniconda3/conda-bld/noarch
Can't build /Users/mortonjt/Dropbox/UCSD/research/conda-recipes/recipes/gneiss due to unsatisfiable dependencies:
Package missing in current osx-64 channels: 
  - scikit-bio ==0.5.1
```

Now, one solution to this is to have the conda recipe uploaded in this github repository.  It looks like packages within this repository have a higher priority over the packages in anaconda.

**Comment by jairideout** [comment]
> Will that be available in the anaconda channel eventually?

Probably -- 0.5.0 eventually became available in the main channel. But we don't have any control over this and don't know when/if that will happen for 0.5.1.

> Now, one solution to this is to have the conda recipe uploaded in this github repository. It looks like packages within this repository have a higher priority over the packages in anaconda.

Does it work if you supply `-c biocore` to your `conda build` command?

**Comment by mortonjt** [comment]
@RNAer @wasade looks like python 3.6 is being installed.  Any idea what is going on?

**Comment by mortonjt** [comment]
Here's the error message in question.

screen shot 2017-03-06 at 9 10 26 am

**Comment by RNAer** [comment]
qiime2 does not compatible with py3.6. it is fine to merge if p35 versions
pass.

**Pull request merged**
